# Generated by Django 3.1.5 on 2021-01-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="label",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="question",
            name="label",
            field=models.TextField(),
        ),
    ]
