# Generated by Django 3.0.5 on 2020-05-03 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogs', '0002_auto_20200414_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-id']},
        ),
    ]
