# Generated by Django 3.1.6 on 2021-02-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogs', '0003_auto_20200503_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='user_type',
            field=models.CharField(max_length=20),
        ),
    ]
