# Generated by Django 2.2.5 on 2019-09-10 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xarala.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=xarala.utils.upload_image_path
                    ),
                ),
                (
                    "resource_link",
                    models.CharField(blank=True, max_length=240, null=True),
                ),
                ("video_id", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Youtube", "Youtube"),
                            ("Vimeo", "Vimeo"),
                            ("Wista", "Wista"),
                            ("Custom", "Custom"),
                        ],
                        default="Youtube",
                        max_length=50,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="course.Chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("is_free", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=13),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Débutant", "Débutant"),
                            ("Moyen", "Moyen"),
                            ("Intermédiaire", "Intermédiaire"),
                        ],
                        default="Débutant",
                        max_length=150,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="course.Category"),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="courses_enrolled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chapter",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course.Course",
            ),
        ),
    ]
