# Generated by Django 2.2.5 on 2019-10-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
