# Generated by Django 3.0.1 on 2019-12-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_lesson_cloudinary_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='cloudinary_file',
        ),
    ]
