# Generated by Django 3.0.1 on 2020-01-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_auto_20191227_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_video",
            field=models.BooleanField(default=True),
        ),
    ]
