# Generated by Django 3.0.2 on 2020-01-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_lesson_is_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='course',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
