# Generated by Django 3.0.2 on 2020-02-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0011_auto_20200126_2358"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
