# Generated by Django 3.0.5 on 2020-04-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_course_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
