# Generated by Django 3.0.5 on 2020-05-04 00:52

from django.db import migrations, models
import xarala.utils


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0014_course_original_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=xarala.utils.upload_image_path
            ),
        ),
    ]
