# Generated by Django 3.0.5 on 2020-05-04 00:56

from django.db import migrations, models
import xarala.utils


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=xarala.utils.upload_image_path),
        ),
    ]
