# Generated by Django 3.0.6 on 2020-07-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0017_auto_20200504_0156"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="projects",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="promote_video",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="target_audience",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="what_will_i_learn",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="lesson",
            name="preview",
            field=models.BooleanField(default=False),
        ),
    ]
