# Generated by Django 3.0.6 on 2020-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0018_auto_20200718_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lecture_number",
            field=models.IntegerField(default=1),
        ),
    ]
