# Generated by Django 3.0.8 on 2020-07-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0020_course_publish_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="resource_link",
            new_name="video_url",
        ),
    ]
