# Generated by Django 3.1.6 on 2021-02-15 07:19

import course.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_chapter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='order',
            field=course.fields.OrderField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=course.fields.OrderField(blank=True, null=True),
        ),
    ]
