# Generated by Django 3.1.6 on 2021-02-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0025_auto_20210215_0719"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="chapter_number",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="lecture_number",
        ),
    ]
