# Generated by Django 3.1.6 on 2021-02-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_auto_20210215_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='uil-arrow', max_length=50),
        ),
    ]
