# Generated by Django 3.1.6 on 2021-02-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
