# Generated by Django 3.0.8 on 2020-07-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200110_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_published',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_updated',
            new_name='updated',
        ),
    ]
