# Generated by Django 3.1.5 on 2021-01-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20200720_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(default="dans cet article, vous allez..."),
        ),
    ]
