# Generated by Django 3.1.6 on 2021-03-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
