# Generated by Django 2.2.5 on 2019-09-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20190922_1807"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="designation",
        ),
        migrations.DeleteModel(
            name="Designation",
        ),
    ]
