# Generated by Django 3.0.6 on 2020-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20200416_1639"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
