# Generated by Django 3.0.6 on 2020-06-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20200630_0828"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ST", "Student"),
                    ("TC", "Teacher"),
                    ("MT", "Mentor"),
                    ("WT", "Writer"),
                ],
                default="ST",
                max_length=10,
                null=True,
            ),
        ),
    ]
