# Generated by Django 3.0.6 on 2020-06-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_auto_20200630_0842"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_type",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_writer",
            field=models.BooleanField(default=False),
        ),
    ]
