# Generated by Django 3.0.5 on 2020-04-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('rule', models.CharField(blank=True, max_length=150, null=True)),
                ('enterprise', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
