# Generated by Django 3.1.5 on 2021-01-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="first_name",
            new_name="full_name",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="last_name",
        ),
    ]
