# Generated by Django 2.2.5 on 2019-09-22 17:51

from django.db import migrations, models
import xarala.utils


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20190922_1749"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=xarala.utils.upload_image_path
            ),
        ),
    ]
