# Generated by Django 2.2.5 on 2019-09-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
