# Generated by Django 2.2.5 on 2019-09-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190922_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='short_description',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
