# Generated by Django 3.1.6 on 2021-03-05 20:27

from django.db import migrations, models
import xarala.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0028_course_submitted'),
        ('blog', '0008_auto_20210303_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('thumbnail', models.ImageField(null=True, upload_to=xarala.utils.upload_image_path)),
                ('description', models.TextField()),
                ('path_type', models.CharField(choices=[('Cours', 'Cours'), ('Tutoriel', 'Tutoriel')], max_length=10)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(to='course.Course')),
                ('tutorials', models.ManyToManyField(to='blog.Post')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
